import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 2,
    padding: 10,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContainer1: {
    flex: 4,
    width: 200,
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    color: 'rgb(116, 144, 147)',
  },
  buttonContainer2: {
    flex: 2,
    width: 200,
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
  },
  buttonContainer3: {
    flex: 1,
    width: 200,
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
  },
  textContainer: {
    fontSize: 16,
  },
  touchContainer: {
    padding: 3,
    flexDirection: 'row',
    backgroundColor: '#fff',
    alignSelf: 'stretch',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  iconContainer: {
    color: 'white',
    alignSelf: 'stretch',
    backgroundColor: 'rgb(116, 144, 147)',
    fontSize: 35,
    borderRadius: 100,
    paddingVertical: 10,
    paddingHorizontal: 15,
    padding: -200,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  buttonContainer: {
    backgroundColor: 'rgb(116, 144, 147)',
    fontSize: 20,
    color: 'white',
    borderRadius: 15,
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  animationContainer: {
    flex: 4,
    width: 300,
    height: 300,
    marginTop: 40,
    resizeMode: 'contain',
    justifyContent: 'center',
    borderRadius: 150,
    backgroundColor: 'rgb(250, 242, 233)',
  },
  animationStyle: {
    width: 300,
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 4,
    marginBottom: -10,
  },
  dialogContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

export default styles;